// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STINProject.Server.Services.PersistenceService;

#nullable disable

namespace STINProject.Server.Migrations
{
    [DbContext(typeof(SQLiteDataContext))]
    [Migration("20230518082519_Sample-Data")]
    partial class SampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("STINProject.Server.Services.PersistenceService.Models.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = new Guid("bf61e44f-dc39-4aa3-8f7e-a66b051b8a17"),
                            Balance = 100.0,
                            Currency = "CZK",
                            OwnerId = new Guid("fc9937db-a031-48ad-9397-088d3c3cfdac")
                        },
                        new
                        {
                            AccountId = new Guid("003bceb8-2bf6-4083-a691-6adefbef9088"),
                            Balance = 0.0,
                            Currency = "USD",
                            OwnerId = new Guid("fc9937db-a031-48ad-9397-088d3c3cfdac")
                        });
                });

            modelBuilder.Entity("STINProject.Server.Services.PersistenceService.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("TransactionID");

                    b.HasIndex("AccountID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("STINProject.Server.Services.PersistenceService.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("fc9937db-a031-48ad-9397-088d3c3cfdac"),
                            Email = "sampleuser@gmail.com",
                            Password = "password",
                            Username = "sampleuser"
                        });
                });

            modelBuilder.Entity("STINProject.Server.Services.PersistenceService.Models.Account", b =>
                {
                    b.HasOne("STINProject.Server.Services.PersistenceService.Models.User", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("STINProject.Server.Services.PersistenceService.Models.Transaction", b =>
                {
                    b.HasOne("STINProject.Server.Services.PersistenceService.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("STINProject.Server.Services.PersistenceService.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("STINProject.Server.Services.PersistenceService.Models.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
